2023-10-04 23:18:37,794 - root - ERROR - ws_client.py - __init__ : 24 - device robot ws://didier.local:4421 down
2023-10-04 23:18:42,847 - root - ERROR - ws_client.py - __init__ : 24 - device sceno ws://sceno.local:4421 down
2023-10-04 23:18:47,906 - root - ERROR - ws_client.py - __init__ : 24 - device harddrive ws://disk.local:4421 down
2023-10-04 23:18:47,989 - root - INFO - main.py - <module> : 21 - Starting control device gp
2023-10-04 23:18:48,003 - root - ERROR - main.py - main : 34 - No module named 'digitalio'
Traceback (most recent call last):
  File "/home/dadou/Nextcloud/Didier/python/dadou_control/main.py", line 28, in main
    from dadoucontrol.gui.gamepad import GamePadGui
  File "/home/dadou/Nextcloud/Didier/python/dadou_control/dadoucontrol/gui/gamepad.py", line 10, in <module>
    from dadoucontrol.buttons.gp_buttons import GPButtons
  File "/home/dadou/Nextcloud/Didier/python/dadou_control/dadoucontrol/buttons/gp_buttons.py", line 4, in <module>
    import digitalio
ModuleNotFoundError: No module named 'digitalio'
